import { processByKey, byId, systems, dataObjects } from './catalog.mjs';
import { patternToInterfaceSemantics } from './integration-decision.mjs';

const INTERFACE_SPEC_VERSION = '1.0';
const PROCESS_CONTRACT_VERSION = '0.2';

const GUARANTEES = new Set(['at-most-once', 'at-least-once', 'effectively-once', 'best-effort']);
const ORDERING = new Set(['none', 'global', 'per-key']);
const RETRY_STRATEGIES = new Set(['none', 'manual', 'automatic']);
const CONTRACT_FORMATS = new Set(['IDoc', 'SOAP', 'REST', 'OData', 'Kafka', 'JMS', 'CSV', 'JSON', 'XML', 'EDI', 'File']);
const INTERFACE_PATTERNS = new Set(['request-response', 'event-driven', 'message-driven', 'file-transfer', 'scheduled-batch']);
const INTERFACE_MODES = new Set(['sync', 'async', 'batch']);

function integrationInterfaceId(integration) {
  const stem = integration.id
    .replace(/^integration\./, '')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .toUpperCase();
  return `EAC-${stem}`.slice(0, 64);
}

function composerUri(kind, id) {
  return `eac://enterprise-architecture-composer/${kind}/${encodeURIComponent(id)}`;
}

function integrationIdsForProcess(process) {
  return (process.integrationNeeds ?? [])
    .map((need) => `integration.${need.id.replace(/^need\./, '')}`)
    .sort((a, b) => a.localeCompare(b));
}

export function exportProcessAsCodeStarter(result, processIdOrKey) {
  const process = result.blueprint.processes.find((item) => item.id === processIdOrKey || item.key === processIdOrKey)
    ?? processByKey(processIdOrKey);
  if (!process) throw new Error(`Process not found in composition: ${processIdOrKey}`);
  if (!result.blueprint.processes.some((item) => item.id === process.id)) {
    throw new Error(`Process is not part of the composed scope: ${process.id}`);
  }

  const interfaceIds = integrationIdsForProcess(process)
    .filter((id) => result.blueprint.integrations.some((item) => item.id === id));

  const systemCatalog = (process.systemIds ?? [])
    .filter((id) => result.blueprint.systems.some((item) => item.id === id))
    .map((id) => {
      const system = byId(systems, id);
      return { id, name: system?.name ?? id, description: system?.description };
    });

  const objectCatalog = (process.dataIds ?? [])
    .filter((id) => result.blueprint.dataObjects.some((item) => item.id === id))
    .map((id) => {
      const object = byId(dataObjects, id);
      return { id, name: object?.name ?? id, description: object?.description };
    });

  const interfaceCatalog = interfaceIds.map((id) => {
    const integration = result.blueprint.integrations.find((item) => item.id === id);
    return { id, name: integration?.name ?? id, description: integration ? `${integration.source} → ${integration.target}; proposed ${integration.patternName}` : undefined };
  });

  return {
    version: PROCESS_CONTRACT_VERSION,
    process: {
      id: process.id,
      name: process.name,
      description: `${process.description} Starter scope generated by Enterprise Architecture Composer; detailed business steps remain intentionally unresolved.`,
      start: 'refine_process_flow',
      tags: [
        'composer:starter',
        ...[...(process.capabilityIds ?? [])].sort().map((id) => `capability:${id}`)
      ]
    },
    systems: systemCatalog,
    objects: objectCatalog,
    interfaces: interfaceCatalog,
    artifacts: [
      {
        id: 'composer_proposal',
        kind: 'enterprise-architecture-composer',
        relation: 'proposed-from',
        uri: composerUri('process', process.id)
      }
    ],
    steps: [
      {
        id: 'refine_process_flow',
        name: `Refine ${process.name} business flow`,
        type: 'subprocess',
        process_ref: composerUri('process', process.id),
        objects: objectCatalog.map((item) => item.id),
        interfaces: interfaceCatalog.map((item) => item.id),
        agent: {
          exposable: true,
          executable: false,
          allowed_actions: ['explain_scope', 'list_systems', 'list_interfaces', 'list_open_decisions']
        },
        transitions: [{ to: 'process_model_ready' }]
      },
      {
        id: 'process_model_ready',
        name: 'Detailed process model accepted by process owner',
        type: 'end'
      }
    ],
    extensions: {
      composer: {
        status: 'starter-not-adopted',
        engineVersion: result.engineVersion,
        catalogVersion: result.catalogVersion,
        sourceProcessId: process.id,
        capabilityIds: [...(process.capabilityIds ?? [])].sort(),
        warning: 'Composer does not infer human tasks, approvals, gateways or business sequencing that are not present in its architecture catalog.'
      }
    }
  };
}

export function validateProcessAsCodeStarter(document) {
  const errors = [];
  if (document?.version !== PROCESS_CONTRACT_VERSION) errors.push('version must be 0.2');
  if (!document?.process?.id || !document?.process?.name) errors.push('process.id and process.name are required');
  if (!Array.isArray(document?.steps) || document.steps.length < 1) errors.push('steps must contain at least one step');
  for (const step of document?.steps ?? []) {
    if (!step.id || !step.name) errors.push('each step requires id and name');
  }
  return { valid: errors.length === 0, contractVersion: PROCESS_CONTRACT_VERSION, errors };
}

function triggerFromIntegration(integration) {
  const purpose = integration.decisionAnalysis?.drivers?.purpose;
  if (purpose === 'business-event' || integration.patternId === 'pattern.domain-event') return { event: integration.name };
  if (integration.mode === 'batch') return { schedule: 'TBD-by-adopter' };
  return { operation: integration.name };
}

export function createInterfaceAsCodeProposal(result, integrationId) {
  const integration = result.blueprint.integrations.find((item) => item.id === integrationId);
  if (!integration) throw new Error(`Integration not found in composition: ${integrationId}`);
  const semantics = patternToInterfaceSemantics(integration.decisionAnalysis?.recommendedPatternId ?? integration.patternId)
    ?? patternToInterfaceSemantics(integration.patternId);

  const unresolved = [
    { field: 'contract.format', reason: 'Composer knows the integration style but not the adopted wire/message format.', options: semantics?.suggestedFormats ?? [], requiredForAdoption: true },
    { field: 'delivery.guarantee', reason: 'Delivery guarantee is an operational contract decision.', options: [...GUARANTEES], requiredForAdoption: true },
    { field: 'delivery.idempotency.required', reason: 'Duplicate-handling semantics require domain/runtime confirmation.', options: [true, false], requiredForAdoption: true },
    { field: 'retry.strategy', reason: 'Retry strategy depends on runtime and support ownership.', options: [...RETRY_STRATEGIES], requiredForAdoption: true },
    { field: 'monitoring.owner', reason: 'Operational ownership is not inferred by the architecture composer.', requiredForAdoption: true },
    { field: 'monitoring.support_route', reason: 'Support route is organization-specific.', requiredForAdoption: true },
    { field: 'reconciliation.key', reason: 'The architecture data object is not necessarily the runtime business key.', requiredForAdoption: true },
    { field: 'reconciliation.frequency', reason: 'Reconciliation cadence depends on business criticality and operating model.', requiredForAdoption: true },
    { field: 'reconciliation.source_of_truth', reason: 'The authoritative runtime system must be explicitly accepted.', requiredForAdoption: true }
  ];

  return {
    format: 'enterprise-architecture-composer/interface-proposal',
    formatVersion: '0.1',
    compatibilityTarget: {
      product: 'interface-as-code',
      specVersion: INTERFACE_SPEC_VERSION,
      schema: 'https://raw.githubusercontent.com/dkharlanau/interface-as-code/main/spec/v1.0/interface.schema.json'
    },
    readyForAdoption: false,
    known: {
      interface: {
        id: integrationInterfaceId(integration),
        name: integration.name,
        source: { system: integration.source, object: integration.dataObject },
        target: { system: integration.target, object: integration.dataObject },
        mode: semantics?.mode ?? integration.mode,
        pattern: semantics?.pattern,
        lifecycle: 'proposed'
      },
      trigger: triggerFromIntegration(integration),
      mapping: { notes: 'No field mapping is inferred by Composer. Link Mapping-as-Code or document mapping explicitly before approval.' },
      security: integration.partnerBoundary ? { external_exposure: true } : undefined
    },
    unresolved,
    provenance: {
      composerIntegrationId: integration.id,
      composerPatternId: integration.patternId,
      recommendedPatternId: integration.decisionAnalysis?.recommendedPatternId ?? integration.patternId,
      ruleIds: [...(integration.ruleIds ?? [])].sort(),
      because: [...(integration.because ?? [])],
      source: composerUri('integration', integration.id),
      engineVersion: result.engineVersion,
      catalogVersion: result.catalogVersion
    }
  };
}

function requiredText(decisions, field, errors) {
  const value = decisions?.[field];
  if (typeof value !== 'string' || value.trim().length < 1) errors.push(`${field} is required`);
  return value;
}

export function adoptInterfaceAsCodeProposal(proposal, decisions = {}) {
  if (proposal?.format !== 'enterprise-architecture-composer/interface-proposal') {
    throw new Error('Not an Enterprise Architecture Composer interface proposal.');
  }
  const errors = [];
  const format = decisions.contractFormat;
  const guarantee = decisions.deliveryGuarantee;
  const idempotencyRequired = decisions.idempotencyRequired;
  const retryStrategy = decisions.retryStrategy;

  if (!CONTRACT_FORMATS.has(format)) errors.push('contractFormat must be an Interface-as-Code v1.0 contract format');
  if (!GUARANTEES.has(guarantee)) errors.push('deliveryGuarantee must be an Interface-as-Code v1.0 delivery guarantee');
  if (typeof idempotencyRequired !== 'boolean') errors.push('idempotencyRequired must be boolean');
  if (!RETRY_STRATEGIES.has(retryStrategy)) errors.push('retryStrategy must be an Interface-as-Code v1.0 retry strategy');

  const monitoringOwner = requiredText(decisions, 'monitoringOwner', errors);
  const supportRoute = requiredText(decisions, 'supportRoute', errors);
  const reconciliationKey = requiredText(decisions, 'reconciliationKey', errors);
  const reconciliationFrequency = requiredText(decisions, 'reconciliationFrequency', errors);
  const sourceOfTruth = requiredText(decisions, 'sourceOfTruth', errors);

  if (decisions.ordering !== undefined && !ORDERING.has(decisions.ordering)) errors.push('ordering is not valid for Interface-as-Code v1.0');
  if (errors.length) return { ready: false, errors, document: null };

  const known = proposal.known;
  const document = {
    version: INTERFACE_SPEC_VERSION,
    interface: known.interface,
    trigger: known.trigger,
    contract: { format },
    delivery: {
      guarantee,
      ...(decisions.ordering ? { ordering: decisions.ordering } : {}),
      idempotency: {
        required: idempotencyRequired,
        ...(idempotencyRequired && decisions.idempotencyKey ? { key: decisions.idempotencyKey } : {})
      }
    },
    mapping: known.mapping,
    retry: {
      strategy: retryStrategy,
      ...(decisions.maxAttempts ? { max_attempts: decisions.maxAttempts } : {}),
      ...(decisions.backoff ? { backoff: decisions.backoff } : {}),
      ...(decisions.deadLetter ? { dead_letter: decisions.deadLetter } : {}),
      ...(decisions.replay ? { replay: decisions.replay } : {})
    },
    monitoring: {
      owner: monitoringOwner,
      support_route: supportRoute,
      ...(decisions.monitoringSignals?.length ? { signals: [...new Set(decisions.monitoringSignals)].sort() } : {}),
      ...(decisions.businessKey ? { business_key: decisions.businessKey } : {})
    },
    reconciliation: {
      key: reconciliationKey,
      frequency: reconciliationFrequency,
      source_of_truth: sourceOfTruth,
      ...(decisions.comparison ? { comparison: decisions.comparison } : {})
    },
    ...(known.security ? { security: known.security } : {}),
    evidence: [
      {
        type: 'design',
        ref: {
          kind: 'custom',
          uri: proposal.provenance.source
        },
        status: 'proposed-by-composer'
      }
    ]
  };

  const validation = validateInterfaceAsCodeV10(document);
  return { ready: validation.valid, errors: validation.errors, document };
}

export function validateInterfaceAsCodeV10(document) {
  const errors = [];
  if (document?.version !== INTERFACE_SPEC_VERSION) errors.push('version must be 1.0');
  const iface = document?.interface;
  if (!iface?.id || !/^[A-Z0-9][A-Z0-9._-]{2,63}$/.test(iface.id)) errors.push('interface.id does not match v1.0 pattern');
  if (!iface?.name || iface.name.length < 3) errors.push('interface.name is required');
  if (!iface?.source?.system || !iface?.target?.system) errors.push('interface source/target system are required');
  if (!INTERFACE_MODES.has(iface?.mode)) errors.push('interface.mode is invalid');
  if (iface?.pattern && !INTERFACE_PATTERNS.has(iface.pattern)) errors.push('interface.pattern is invalid');
  if (!document?.trigger || Object.keys(document.trigger).length < 1) errors.push('trigger is required');
  if (!CONTRACT_FORMATS.has(document?.contract?.format)) errors.push('contract.format is invalid');
  if (!GUARANTEES.has(document?.delivery?.guarantee)) errors.push('delivery.guarantee is invalid');
  if (typeof document?.delivery?.idempotency?.required !== 'boolean') errors.push('delivery.idempotency.required is required');
  if (document?.delivery?.ordering && !ORDERING.has(document.delivery.ordering)) errors.push('delivery.ordering is invalid');
  if (!RETRY_STRATEGIES.has(document?.retry?.strategy)) errors.push('retry.strategy is invalid');
  if (!document?.monitoring?.owner || !document?.monitoring?.support_route) errors.push('monitoring owner/support_route are required');
  if (!document?.reconciliation?.key || !document?.reconciliation?.frequency || !document?.reconciliation?.source_of_truth) errors.push('reconciliation key/frequency/source_of_truth are required');
  return { valid: errors.length === 0, specVersion: INTERFACE_SPEC_VERSION, errors };
}
